### PR TITLE
Don't return 503 when cassandra is unavailable

### PR DESCRIPTION
**Pull request by keshavdv**
IMO, the sidecar shouldn't overload the HTTP status code based on Cassandra's health since this makes it difficult for other services to reason about where the failure is. A simple example: somebody running a reverse proxy in front of the sidecar for TLS termination. Here, a 503 could mean the sidecar itself is unhealthy, or that the sidecar is available, but Cassandra is unhealthy. Since the remediations for each situation might be different (restart sidecar vs. restart cassandra), I think the sidecar should always return 200 if it's able to generate a response and everything else should just be conveyed within the response.

The version of gradlew that was included didn't seem to run any of the tests from a fresh clone, so this change also includes an update to a new version and some other build-related changes.

### CODE REVIEW

**Comment by keshavdv** [comment]
@dineshjoshi Did you have any thoughts/feedback on this? Would you prefer that this be a follow up PR after the initial version is merged in CASSANDRA-14395?

**Comment by dineshjoshi** [comment]
Hi @keshavdv looks like github auto-closed this PR probably because I force pushed to the repo. Why do you think returning a HTTP 503 would make it hard to reason about the state of the system? I am planning on including a separate health check for the sidecar itself, coordinator and the cluster as a whole. So you will be able to distinguish and reason about the state of the system.

The point about running a forward proxy is great and normally you should be able to tell the difference between the proxy sending a HTTP 503 vs the origin server sending a HTTP 503 because when the sidecar responds with a 503, it still sends a JSON payload with more information. This would not happen with the proxy sending back a 503.

**Comment by keshavdv** [comment]
I love the momentum on the sidecar and am excited to see it getting it closer to being merged! 

Because the status code is now conveying both data and control information, some of the typical web paradigms no longer apply. We can't just treat a non-2xx as a "we couldn't talk to the sidecar"; we always have to pay the cost of attempting to decode the response as JSON to see if it's an actual failure (and as devil's advocate, what happens if the reverse proxy in between also served a valid JSON body alongside a 503?).

**Comment by dineshjoshi** [comment]
So, you don't have to parse the JSON. Thats the whole point of the HTTP Error code. You parse the JSON if you want to learn the details of the failure. You can treat the 503 as Cassandra Service being unavailable. The reverse proxies are not expected to modify the contents of the response body.

**Comment by keshavdv** [comment]
Since the error code now can mean different things, it isn't easily distinguishable what type of error we might be hitting. A reverse proxy could respond with 503 and `{"status": "SERVER_UNAVAILABLE"}` because it couldn't talk to the upstream sidecar process. This is totally valid since the proxy isn't modifying any response, it's simply generating its own that happens to clash with our schema. Without parsing the JSON, it's impossible to differentiate a 503 indicating a sidecar failure or a Cassandra failure. Even with parsing the JSON, because the status code is overridden, it's impossible to tell _who_ generated that status code. In this scenario, importantly, it's possible to get the answer wrong (we think Cassandra is unhealthy when it actually is running). 

In my opinion, not overloading this feels more straightforward. A 200 response, regardless of what sits in between, is always guaranteed to have come from the sidecar and it can always be assumed that the JSON body is the source of truth of information. Any other response code would indicate that we can make no claim about the state of Cassandra or the sidecar process.

**Comment by dineshjoshi** [comment]
The core issue you're raising is about distinguishing the status code that your origin server generated vs proxy's status code. AFAIK there isn't anything in the HTTP Standard that prevents proxies from altering the error codes or overriding them. However, what a sensible proxy would do is setup custom error codes so that the users can distinguish between the codes that the origin server generated and the proxy's error codes. For example, Cloudflare does just this - https://support.cloudflare.com/hc/en-us/articles/115003011431/ Most proxy middleware declare the kind of HTTP status codes they return vs what they pass through.

That said, I am not sure why would you want to put the sidecars behind a reverse proxy as each individual instance is unique and they're not interchangeable.

**Pull request closed without merging**
